export const LS_KEYS = {
  history: "ipa-quiz:history:v1",
  starred: "ipa-quiz:starred:v1",
  premium: "ipa-quiz:premium:v1",
  theme: "ipa-quiz:theme:v1",
  aiUsage: "ipa-quiz:ai-usage:v1",
  settings: "ipa-quiz:settings:v1",
  swipeHintShown: "ipa-quiz:swipe-hint-shown:v1",
  chatSessions: "ipa-quiz:chat-sessions:v1",
  motivation: "ipa-quiz:motivation:v1",
  studyDays: "ipa-quiz:study-days:v1",
  earnedBadges: "ipa-quiz:earned-badges:v1",
  premiumCoupon: "ipa-quiz:premium-coupon:v1",
  spacedRepetition: "ipa-quiz:srs:v1",
  examDate: "ipa-quiz:exam-date:v1",
  mockScores: "ipa-quiz:mock-scores:v1",
  rankingNickname: "ipa-quiz:ranking-nickname:v1",
  notificationPrefs: "ipa-quiz:notification-prefs:v1",
  pushSubscription: "ipa-quiz:push-subscription:v1",
  xpState: "ipa-quiz:xp:v1",
  achievements: "ipa-quiz:achievements:v1",
  dailyChallenge: "ipa-quiz:daily-challenge:v1",
  dailyMissions: "ipa-quiz:daily-missions:v1",
  avatar: "ipa-quiz:avatar:v1",
  audioBgm: "ipa-quiz:audio-bgm:v1",
  audioBgmVolume: "ipa-quiz:audio-bgm-volume:v1",
  language: "ipa-quiz:language:v1",
} as const;

export type LSKey = (typeof LS_KEYS)[keyof typeof LS_KEYS];
