import type { ExamCode } from "@/lib/questions/types";

export type QualificationDomain =
  | "information-technology"
  | "finance"
  | "electrical"
  | "construction"
  | "real-estate"
  | "pharmacy"
  | "legal"
  | "safety"
  | "accounting"
  | "welfare";

export type PublicationStatus =
  | "live"
  | "notification-required"
  | "ready-to-ingest"
  | "permission-required"
  | "terms-review-required";

export interface QualificationCatalogEntry {
  slug: string;
  examCode?: ExamCode;
  shortName: string;
  fullName: string;
  domain: QualificationDomain;
  administrator: string;
  officialQuestionsUrl: string;
  officialReuseTermsUrl: string;
  status: PublicationStatus;
  reuseSummary: string;
  attributionTemplate?: string;
  /** 公開前に完了させる作業。空配列は公開可能を意味しない。 */
  remainingWork: string[];
}

/**
 * 外部資格を追加するときの単一の判断台帳。
 * 「公式に問題と正答がある」だけでは live にせず、転載条件まで確認する。
 */
export const QUALIFICATION_CATALOG: readonly QualificationCatalogEntry[] = [
  {
    slug: "fp1",
    examCode: "fp1",
    shortName: "FP1級",
    fullName: "1級ファイナンシャル・プランニング技能検定",
    domain: "finance",
    administrator: "一般社団法人金融財政事情研究会",
    officialQuestionsUrl: "https://www.kinzai.or.jp/fp/news-fp/50623.html",
    officialReuseTermsUrl: "https://www.kinzai.or.jp/ginou/license_terms.html",
    status: "live",
    reuseSummary: "2026年5月学科は基礎50問・応用15原問62回答欄を収録。2026年9月学科は基礎全50問と応用全15原問57回答欄を収録。各原問の正答と全選択肢または回答欄の解説を掲載。",
    attributionTemplate: "出典：一般社団法人金融財政事情研究会 ファイナンシャル・プランニング技能検定1級 学科試験 基礎編（2026年5月・9月）",
    remainingWork: ["法令改正内容の継続確認"],
  },
  {
    slug: "fp3",
    examCode: "fp3",
    shortName: "FP3級",
    fullName: "3級ファイナンシャル・プランニング技能検定",
    domain: "finance",
    administrator: "日本ファイナンシャル・プランナーズ協会",
    officialQuestionsUrl: "https://www.jafp.or.jp/exam/mohan/",
    officialReuseTermsUrl: "https://www.jafp.or.jp/exam/mohan/files/exam_riyou.pdf",
    status: "live",
    reuseSummary: "公式に公表された学科・実技の問題と正答を、年度ごとに収録。",
    attributionTemplate: "出典：日本FP協会 3級ファイナンシャル・プランニング技能検定 学科試験（公表年月）",
    remainingWork: ["2026年公表問題の追加", "法改正影響を受ける問題の失効管理"],
  },
  {
    slug: "fp2",
    examCode: "fp2",
    shortName: "FP2級",
    fullName: "2級ファイナンシャル・プランニング技能検定",
    domain: "finance",
    administrator: "日本ファイナンシャル・プランナーズ協会",
    officialQuestionsUrl: "https://www.jafp.or.jp/exam/mohan/",
    officialReuseTermsUrl: "https://www.jafp.or.jp/exam/mohan/files/exam_riyou.pdf",
    status: "live",
    reuseSummary: "日本FP協会・金融財政事情研究会が公表した学科・実技の問題を収録。",
    attributionTemplate: "出典：日本FP協会 2級ファイナンシャル・プランニング技能検定（公表年月）",
      remainingWork: ["次回公表分の追加", "法改正影響の継続確認"],
  },
  {
    slug: "denken3",
    examCode: "denken3",
    shortName: "電験三種",
    fullName: "第三種電気主任技術者試験",
    domain: "electrical",
    administrator: "電気技術者試験センター",
    officialQuestionsUrl: "https://www.shiken.or.jp/chief/third/qa/",
    officialReuseTermsUrl: "https://www.shiken.or.jp/shiken/faq/faq08/000082.html",
    status: "live",
    reuseSummary: "公式に公表された過去問題と正答を、年度・科目ごとに収録。",
    attributionTemplate: "出典：令和○年度○期第三種電気主任技術者試験 ○○科目",
    remainingWork: ["一般解説のみの2問について全肢解説を独立確認", "数式・図のアクセシビリティを継続改善"],
  },
  {
    slug: "denken1",
    examCode: "denken1",
    shortName: "電験一種",
    fullName: "第一種電気主任技術者試験 一次試験",
    domain: "electrical",
    administrator: "電気技術者試験センター",
    officialQuestionsUrl: "https://www.shiken.or.jp/chief/first/qa/",
    officialReuseTermsUrl: "https://www.shiken.or.jp/shiken/faq/faq08/000082.html",
    status: "live",
    reuseSummary: "2026年度一次試験の従来5原問・25空欄を保持し、2025・2026年度の理論・電力・機械36原問・204回答欄を原問単位でも収録。重複2原問を除いた固有の掲載原問は39件です。公式原図・解答群と各欄の解説を確認できます。",
    attributionTemplate: "出典：令和○年度第一種電気主任技術者一次試験○○科目A問題問○",
    remainingWork: ["両年度の未収録原問（個別HOLDを含む）", "二次試験"],
  },
  {
    slug: "denken2",
    examCode: "denken2",
    shortName: "電験二種",
    fullName: "第二種電気主任技術者試験 一次試験",
    domain: "electrical",
    administrator: "電気技術者試験センター",
    officialQuestionsUrl: "https://www.shiken.or.jp/chief/second/qa/",
    officialReuseTermsUrl: "https://www.shiken.or.jp/shiken/faq/faq08/000082.html",
    status: "live",
    reuseSummary: "2026年度一次試験は理論・電力・機械・法規の30原問・155回答欄、2025年度は理論・機械16原問・80回答欄と電力・法規11原問・55回答欄を収録。計57原問・290回答欄です。公式問題の図・数式・解答群と、各欄の正答・解説を確認できます。",
    attributionTemplate: "出典：令和○年度第二種電気主任技術者一次試験○○科目○問題問○",
    remainingWork: ["2025年度法規の未収録3原問と2024年度以前の未収録原問の追加", "二次試験の追加"],
  },
  {
    slug: "denko2",
    examCode: "denko2",
    shortName: "第二種電気工事士",
    fullName: "第二種電気工事士試験",
    domain: "electrical",
    administrator: "電気技術者試験センター",
    officialQuestionsUrl: "https://www.shiken.or.jp/construction/second/qa/",
    officialReuseTermsUrl: "https://www.shiken.or.jp/shiken/faq/faq08/000082.html",
    status: "live",
    reuseSummary: "公式に公表された過去問題と正答を、年度ごとに収録。",
    attributionTemplate: "出典：令和○年度○期第二種電気工事士学科試験",
    remainingWork: ["令和8年度上期学科の問11〜50の追加"],
  },
  {
    slug: "denko1",
    examCode: "denko1",
    shortName: "第一種電気工事士",
    fullName: "第一種電気工事士試験",
    domain: "electrical",
    administrator: "電気技術者試験センター",
    officialQuestionsUrl: "https://www.shiken.or.jp/construction/first/qa/",
    officialReuseTermsUrl: "https://www.shiken.or.jp/shiken/faq/faq08/000082.html",
    status: "live",
    reuseSummary: "令和8年度上期学科試験(CBT)で公表された出題例の全50問(一般問題40問・配線図問題10問)と各選択肢の解説を収録。",
    attributionTemplate: "出典：令和○年度第一種電気工事士○期学科試験",
    remainingWork: ["令和7年度下期など過去の学科試験の追加", "技能試験(候補問題・欠陥判断基準)の掲載検討"],
  },
  {
    slug: "sekou-doboku2",
    examCode: "civil2",
    shortName: "2級土木施工管理",
    fullName: "2級土木施工管理技術検定",
    domain: "construction",
    administrator: "全国建設研修センター",
    officialQuestionsUrl: "https://www.jctc.jp/mondai/",
    officialReuseTermsUrl: "https://www.jctc.jp/mondai/",
    status: "live",
    reuseSummary: "令和8年度前期と令和7年度10月実施分の第一次検定（土木）各全66問と各選択肢の解説を収録。",
    attributionTemplate: "出典：全国建設研修センター ○年度2級土木施工管理技術検定 第一次検定（土木）",
    remainingWork: ["他年度・後期の追加", "工事仕様書の改定に伴う解説更新"],
  },
  {
    slug: "sekou-kankoji2",
    examCode: "kankoji2",
    shortName: "2級管工事施工管理",
    fullName: "2級管工事施工管理技術検定",
    domain: "construction",
    administrator: "全国建設研修センター",
    officialQuestionsUrl: "https://www.jctc.jp/mondai/",
    officialReuseTermsUrl: "https://www.jctc.jp/mondai/",
    status: "live",
    reuseSummary: "令和8年度前期と令和7年度後期の第一次検定を各全52問、各選択肢の解説付きで収録。",
    attributionTemplate: "出典：全国建設研修センター ○年度2級管工事施工管理技術検定 第一次検定（前期／後期）",
    remainingWork: ["他年度の追加", "公共建築工事標準仕様書の改定に伴う解説更新"],
  },
  {
    slug: "sekou-zoen2",
    examCode: "zoen2",
    shortName: "2級造園施工管理",
    fullName: "2級造園施工管理技術検定",
    domain: "construction",
    administrator: "全国建設研修センター",
    officialQuestionsUrl: "https://www.jctc.jp/mondai/",
    officialReuseTermsUrl: "https://www.jctc.jp/mondai/",
    status: "live",
    reuseSummary: "令和8年度前期10問と令和7年度後期27問を公式問題・正答と照合して収録。各回とも全40問中の一部。",
    attributionTemplate: "出典：全国建設研修センター ○年度2級造園施工管理技術検定 第一次検定（前期／後期）",
    remainingWork: ["令和7年度後期の図表を使う問9・16・17・20・22・24・27・28・29・37〜40を確認", "令和7年度後期の未収録13問と令和8年度前期の未収録30問を確認・追加"],
  },
  {
    slug: "sekou-zoen1",
    examCode: "zoen1",
    shortName: "1級造園施工管理",
    fullName: "1級造園施工管理技術検定",
    domain: "construction",
    administrator: "全国建設研修センター",
    officialQuestionsUrl: "https://www.jctc.jp/mondai/",
    officialReuseTermsUrl: "https://www.jctc.jp/mondai/",
    status: "live",
    reuseSummary: "令和8年度の第一次検定の問題A・Bから、公式問題・正答と照合した設問を段階的に収録。",
    attributionTemplate: "出典：全国建設研修センター 令和8年度1級造園施工管理技術検定 第一次検定 試験問題A／B",
    remainingWork: ["同年度の未収録問題・図表の確認と追加", "他年度の追加"],
  },
  {
    slug: "sekou-tsushin2",
    examCode: "tsushin2",
    shortName: "2級電気通信工事施工管理",
    fullName: "2級電気通信工事施工管理技術検定",
    domain: "construction",
    administrator: "全国建設研修センター",
    officialQuestionsUrl: "https://www.jctc.jp/mondai/",
    officialReuseTermsUrl: "https://www.jctc.jp/mondai/",
    status: "live",
    reuseSummary: "令和8年度前期の第一次検定から、公式問題・正答と照合した設問を段階的に収録。",
    attributionTemplate: "出典：全国建設研修センター 令和8年度2級電気通信工事施工管理技術検定 第一次検定（前期）",
    remainingWork: ["同年度の図表を使う問題の確認・追加", "他年度の追加"],
  },
  {
    slug: "sekou-tsushin1",
    examCode: "tsushin1",
    shortName: "1級電気通信工事施工管理",
    fullName: "1級電気通信工事施工管理技術検定",
    domain: "construction",
    administrator: "全国建設研修センター",
    officialQuestionsUrl: "https://www.jctc.jp/mondai/",
    officialReuseTermsUrl: "https://www.jctc.jp/mondai/",
    status: "live",
    reuseSummary: "令和8年度の第一次検定の問題A・Bから、公式問題・正答と照合した設問を段階的に収録。",
    attributionTemplate: "出典：全国建設研修センター 令和8年度1級電気通信工事施工管理技術検定 第一次検定 試験問題A／B",
    remainingWork: ["同年度の未収録問題・図表の確認と追加", "他年度の追加"],
  },
  {
    slug: "kaigo",
    examCode: "kaigo",
    shortName: "介護福祉士",
    fullName: "介護福祉士国家試験",
    domain: "welfare",
    administrator: "社会福祉振興・試験センター",
    officialQuestionsUrl: "https://www.sssc.or.jp/kaigo/past_exam/index.html",
    officialReuseTermsUrl: "https://www.sssc.or.jp/pastissues/index.html",
    status: "live",
    reuseSummary: "第38回（令和7年度）の全125問（総合問題・図の問題を含む）と全選択肢の解説を収録。",
    attributionTemplate: "出典：公益財団法人社会福祉振興・試験センター 第○回介護福祉士国家試験 問題○",
    remainingWork: ["第37回・第36回の追加", "法改正で成立しなくなった問題の失効管理"],
  },
  {
    slug: "shakai",
    examCode: "shakai",
    shortName: "社会福祉士",
    fullName: "社会福祉士国家試験",
    domain: "welfare",
    administrator: "社会福祉振興・試験センター",
    officialQuestionsUrl: "https://www.sssc.or.jp/shakai/past_exam/index.html",
    officialReuseTermsUrl: "https://www.sssc.or.jp/pastissues/index.html",
    status: "live",
    reuseSummary: "第38回（令和7年度）の全129問（共通科目84問・専門科目45問）と全選択肢の解説を収録。",
    attributionTemplate: "出典：公益財団法人社会福祉振興・試験センター 第○回社会福祉士国家試験 問題○",
    remainingWork: ["第37回・第36回の追加", "法改正で成立しなくなった問題の失効管理"],
  },
  {
    slug: "seishin",
    examCode: "seishin",
    shortName: "精神保健福祉士",
    fullName: "精神保健福祉士国家試験",
    domain: "welfare",
    administrator: "社会福祉振興・試験センター",
    officialQuestionsUrl: "https://www.sssc.or.jp/seishin/past_exam/index.html",
    officialReuseTermsUrl: "https://www.sssc.or.jp/pastissues/index.html",
    status: "live",
    reuseSummary: "第28回（令和7年度）の専門科目48問・共通科目84問と、第27回（令和6年度）の専門科目48問・共通科目81問、全選択肢の解説を収録。",
    attributionTemplate: "出典：公益財団法人社会福祉振興・試験センター 第○回精神保健福祉士国家試験 問題○",
    remainingWork: ["第27回共通科目の保留3問（問題4・69・76）の原典照合", "第26回以前は旧カリキュラムのため収録方針の決定", "法改正で成立しなくなった問題の失効管理"],
  },
  {
    slug: "sekou-kenchiku1",
    shortName: "1級建築施工管理",
    fullName: "1級建築施工管理技術検定",
    domain: "construction",
    administrator: "建設業振興基金",
    officialQuestionsUrl: "https://www.fcip-shiken.jp/about/",
    officialReuseTermsUrl: "https://www.fcip-shiken.jp/about/",
    status: "permission-required",
    reuseSummary: "公式ページは問題・正答肢を公開する一方、掲載記事・写真・図表の転載を禁止。",
    remainingWork: ["試験実施機関からWeb問題集への転載許諾を取得", "許諾条件に従い出典表記を確定"],
  },
  {
    slug: "sekou-denki1",
    shortName: "1級電気工事施工管理",
    fullName: "1級電気工事施工管理技術検定",
    domain: "construction",
    administrator: "建設業振興基金",
    officialQuestionsUrl: "https://www.fcip-shiken.jp/about/",
    officialReuseTermsUrl: "https://www.fcip-shiken.jp/about/",
    status: "permission-required",
    reuseSummary: "建築施工管理と同じページに転載禁止表示がある。",
    remainingWork: ["試験実施機関からWeb問題集への転載許諾を取得"],
  },
  {
    slug: "sekou-doboku1",
    examCode: "civil1",
    shortName: "1級土木施工管理",
    fullName: "1級土木施工管理技術検定",
    domain: "construction",
    administrator: "全国建設研修センター",
    officialQuestionsUrl: "https://www.jctc.jp/mondai/",
    officialReuseTermsUrl: "https://www.jctc.jp/mondai/",
    status: "live",
    reuseSummary: "令和8年度（7月実施）の第一次検定から、試験問題A全66問と試験問題B 34問を各選択肢の解説付きで収録。",
    attributionTemplate: "出典：全国建設研修センター ○年度1級土木施工管理技術検定 第一次検定 試験問題A／B",
    remainingWork: ["試験問題B No.7の解説確定と追加", "令和7年度分の追加"],
  },
  {
    slug: "takken",
    examCode: "takken",
    shortName: "宅建",
    fullName: "宅地建物取引士資格試験",
    domain: "real-estate",
    administrator: "不動産適正取引推進機構",
    officialQuestionsUrl: "https://www.retio.or.jp/exam/past_ques_ans/other/",
    officialReuseTermsUrl: "https://www.retio.or.jp/copyright/",
    status: "live",
    reuseSummary: "2024・2025年度の公式問題・正解番号表を掲載し、各年度の解説に法令基準日を表示。",
    remainingWork: [],
  },
  {
    slug: "tohan-kansai",
    examCode: "tohan",
    shortName: "登録販売者（関西）",
    fullName: "登録販売者試験（関西広域連合：滋賀・京都・大阪・兵庫・和歌山・奈良・徳島）",
    domain: "pharmacy",
    administrator: "関西広域連合",
    officialQuestionsUrl: "https://www.kouiki-kansai.jp/koikirengo/jisijimu/shikakumenkyo/touroku/7607.html",
    officialReuseTermsUrl: "https://www.kouiki-kansai.jp/site/221.html",
    status: "live",
    reuseSummary: "令和7年度（2025年8月23日実施）の全120問と各選択肢の解説を収録。",
    attributionTemplate: "出典：関西広域連合 令和○年度 登録販売者試験（前半／後半）問○",
    remainingWork: ["令和8年度は公式の「正答(例)」のみで確定正答の公表待ち", "他の年度（令和元〜6年度）の追加", "東京都・神奈川県など他ブロックは個別に確認"],
  },
  {
    slug: "kanri",
    examCode: "kanri",
    shortName: "管理業務主任者",
    fullName: "管理業務主任者試験",
    domain: "real-estate",
    administrator: "一般社団法人マンション管理業協会",
    officialQuestionsUrl: "https://www.kanrikyo.or.jp/kanri/mondaiseikai/index.html",
    officialReuseTermsUrl: "https://www.kanrikyo.or.jp/kanri/pdf/kakomonshiyou.pdf",
    status: "live",
    reuseSummary: "令和6年度・令和7年度の公式問題を、公式正答と学習用の全選択肢解説付きで演習できます。掲載数は現在演習できる問題の数です。",
    attributionTemplate: "出典：令和○年度 管理業務主任者試験問題 問○",
    remainingWork: ["令和7年度の残る34問を公式正答・一次根拠と照合", "令和8年度試験の公表後に法令基準日を確認して追加"],
  },
  {
    slug: "gyoseishoshi",
    shortName: "行政書士",
    fullName: "行政書士試験",
    domain: "legal",
    administrator: "行政書士試験研究センター",
    officialQuestionsUrl: "https://www.gyosei-shiken.or.jp/",
    officialReuseTermsUrl: "https://gyosei-shiken.or.jp/doc/about/copyright.html",
    status: "permission-required",
    reuseSummary: "書籍・ホームページ等への掲載にはセンターの許諾が必要。",
    remainingWork: ["掲載許諾を申請", "第三者著作物により非公開の設問を除外"],
  },
  {
    slug: "eisei1",
    examCode: "eisei1",
    shortName: "第一種衛生管理者",
    fullName: "第一種衛生管理者免許試験",
    domain: "safety",
    administrator: "安全衛生技術試験協会",
    officialQuestionsUrl: "https://www.exam.or.jp/lckohyo/",
    officialReuseTermsUrl: "https://www.exam.or.jp/lckohyo/",
    status: "live",
    reuseSummary: "2025年10月・2026年4月の公表試験各44問、計88問を公式問題・正答と照合して収録。",
    attributionTemplate: "出典：安全衛生技術試験協会 令和8年4月公表 第一種衛生管理者免許試験",
    remainingWork: ["2026年1月以降に施行された法令を扱う問題は別途更新確認"],
  },
  {
    slug: "eisei2",
    examCode: "eisei2",
    shortName: "第二種衛生管理者",
    fullName: "第二種衛生管理者免許試験",
    domain: "safety",
    administrator: "安全衛生技術試験協会",
    officialQuestionsUrl: "https://www.exam.or.jp/lckohyo/",
    officialReuseTermsUrl: "https://www.exam.or.jp/lckohyo/",
    status: "live",
    reuseSummary: "2025年10月・2026年4月の公表試験各30問、計60問を公式問題・正答と照合して収録。",
    attributionTemplate: "出典：安全衛生技術試験協会 令和○年○月公表 第二種衛生管理者免許試験",
    remainingWork: ["2026年1月以降に施行された法令を扱う問題は別途更新確認"],
  },
  {
    slug: "gijutsushi-soukan",
    examCode: "soukan",
    shortName: "技術士 総合技術監理部門",
    fullName: "技術士第二次試験 総合技術監理部門（必須科目Ⅰ－1 択一式）",
    domain: "construction",
    administrator: "公益社団法人日本技術士会",
    officialQuestionsUrl: "https://www.engineer.or.jp/c_categories/index02022241.html",
    officialReuseTermsUrl: "https://www.engineer.or.jp/c_categories/index02022241.html",
    status: "live",
    reuseSummary: "令和7年度・令和8年度の択一式を公式問題PDF・正答PDFと照合して収録。日本技術士会に明示の転載条件はなく、衛生管理者と同様に出典を明記し、解説が独自作成で同会と無関係であることを各問に表示する。",
    attributionTemplate: "出典：公益社団法人日本技術士会 令和○年度技術士第二次試験 総合技術監理部門 必須科目 択一式 Ⅰ－1－○",
    remainingWork: ["各年度の問題冊子が示す法令基準日（4月1日）より後の改正は別途更新確認", "記述式（Ⅰ－2）は模範解答が非公開のため収録しない"],
  },
  {
    slug: "hoikushi",
    examCode: "hoikushi",
    shortName: "保育士試験",
    fullName: "保育士試験（筆記9科目）",
    domain: "welfare",
    administrator: "一般社団法人全国保育士養成協議会",
    officialQuestionsUrl: "https://www.hoyokyo.or.jp/exam/pasttest/past-test.html",
    officialReuseTermsUrl: "https://www.hoyokyo.or.jp/terms/",
    status: "live",
    reuseSummary: "公開中は令和8年度前期の筆記試験9科目・1回分154問。令和7年度後期は未公開。",
    attributionTemplate: "出典：一般社団法人全国保育士養成協議会 令和○年度○期保育士試験 筆記試験「○○」問○",
    remainingWork: ["問題転載の許諾根拠を再確認", "令和7年度後期の残5科目・全肢解説・独立査読を準備", "法改正・指針改定の継続確認", "第三者の楽譜・図版の権利と再現性を設問単位で確認"],
  },
  {
    slug: "mankan",
    examCode: "mankan",
    shortName: "マンション管理士",
    fullName: "マンション管理士試験",
    domain: "real-estate",
    administrator: "公益財団法人マンション管理センター",
    officialQuestionsUrl: "https://www.mankan.org/kakomondai.html",
    officialReuseTermsUrl: "https://www.mankan.org/kakomondai.html",
    status: "live",
    reuseSummary: "令和6年度・令和7年度の公式各50問（計100問）を公式問題PDF・正答PDFと照合して収録。マンション管理センターに明示の転載条件の記載はなく、出典を明記し、解説が独自作成で同センターとは無関係であることを各問に表示する公開扱い（司令塔判断）。",
    attributionTemplate: "出典：令和○年度 マンション管理士試験 問○（公益財団法人マンション管理センター）",
    remainingWork: ["令和6年度問40（建築物省エネ法の増築届出基準）は公式正解の法的根拠に一次資料で到達できず保留", "令和8年度試験の公表後に追加を検討"],
  },
  {
    slug: "kashikin",
    examCode: "kashikin",
    shortName: "貸金業務取扱主任者",
    fullName: "貸金業務取扱主任者資格試験",
    domain: "finance",
    administrator: "一般社団法人日本貸金業協会",
    officialQuestionsUrl: "https://www.j-fsa.or.jp/chief/qualifying_exam/exam_example/",
    officialReuseTermsUrl: "https://www.j-fsa.or.jp/chief/qualifying_exam/exam_example/",
    status: "live",
    reuseSummary: "第20回（令和7年度）・第19回（令和6年度）の全50問を公式問題PDF・正答PDFと照合して収録。日本貸金業協会に明示の転載条件はなく、衛生管理者・技術士総合技術監理部門と同様に出典を明記し、解説が独自作成で同協会と無関係であることを各問に表示する。",
    attributionTemplate: "出典：一般社団法人日本貸金業協会 令和○年度（第○回）貸金業務取扱主任者資格試験問題（問題・正答）問○",
    remainingWork: ["各回の問題冊子が示す基準日（試験実施日）より後の法改正は別途更新確認"],
  },
  {
    slug: "sharoushi",
    examCode: "sharoushi",
    shortName: "社会保険労務士",
    fullName: "社会保険労務士試験",
    domain: "legal",
    administrator: "全国社会保険労務士会連合会 試験センター",
    officialQuestionsUrl: "https://www.sharosi-siken.or.jp/results/",
    officialReuseTermsUrl: "https://www.sharosi-siken.or.jp/results/",
    status: "live",
    reuseSummary: "第58回（令和8年度）・第57回（令和7年度）の択一式62原問・全310肢の解説と、選択式16原問・80空欄を原形で収録しています。最新2回の全156原問中78原問の途中公開です。択一式の労基・安衛16原問、労災保険法14原問、雇用保険法7原問、健康保険法14原問、厚生年金保険法5原問、一般常識6原問を一次資料で確認しました。出典と試験時点を各問に表示し、解説は過去問AIの独自作成です。一般掲載の可否はオーナーが確認します。",
    attributionTemplate: "出典：全国社会保険労務士会連合会 試験センター 第○回（令和○年度）社会保険労務士試験 択一式・選択式（加工・解説）",
    remainingWork: ["未収録78原問（択一式のみ）の原典・正答・試験時点資料を確認", "第58回 一般常識 問9の訂正内容は未収録", "一般掲載の可否はオーナー確認"],
  },
  {
    slug: "kangoshi",
    examCode: "kangoshi",
    shortName: "看護師",
    fullName: "看護師国家試験",
    domain: "welfare",
    administrator: "厚生労働省",
    officialQuestionsUrl: "https://www.mhlw.go.jp/seisakunitsuite/bunya/kenkou_iryou/iryou/topics/tp260424-03_04_05.html",
    officialReuseTermsUrl: "https://www.mhlw.go.jp/chosakuken/index.html",
    status: "live",
    reuseSummary: "第115・114回 午前 問1〜90のうち178問収録。午前 問91〜120の確認済み49原問と午後215原問を加え、計442原問を部分収録。第115回は午前114問・午後107問、第114回は午前113問・午後108問です。全1827肢の正誤理由と数値記入2問の計算過程を確認できます。第115回午前 問32は厚生労働省が採点対象から除外したため収録していません。第115回午前 問79と未確認問題・未整備図は未収録です。共通症例は各枝問に保持し、全肢解説と原本画像を照合。出典と加工内容を明示。一般掲載可否の確認はオーナー担当で、許諾取得の記録はありません。",
    attributionTemplate: "出典：厚生労働省「第○回看護師国家試験」午前 問○（問題・正答）",
    remainingWork: ["一般掲載可否のオーナー確認", "第115回午前 問79は根拠確認中", "第115回午前4問・第114回午前7問は根拠確認中", "第115回午後14問・第114回午後23問は根拠・図の確認中", "第115回午前 問32（採点除外）は未採点表示の実装まで未収録"],
  },
  {
    slug: "boki3",
    shortName: "日商簿記3級",
    fullName: "日商簿記検定3級",
    domain: "accounting",
    administrator: "日本商工会議所",
    officialQuestionsUrl: "https://www.kentei.ne.jp/bookkeeping/sample",
    officialReuseTermsUrl: "https://www.kentei.ne.jp/bookkeeping/sample",
    status: "permission-required",
    reuseSummary: "過去問は非公開。サンプル問題も無断転載・無断営利利用を禁止。",
    remainingWork: ["利用許諾を取得できない限り問題本文を収録しない"],
  },
] as const;

export function getQualificationByExamCode(exam: ExamCode): QualificationCatalogEntry | undefined {
  return QUALIFICATION_CATALOG.find((item) => item.examCode === exam);
}

/** Public routes and question registries must call this gate before exposing external data. */
export function isExamPublished(exam: ExamCode): boolean {
  return getQualificationByExamCode(exam)?.status === "live" || !getQualificationByExamCode(exam);
}
