// Auto-generated by scripts/parse-all.ts — do not edit manually.
// Source: IPA 基本情報技術者試験 2024年度秋期 科目B
// Questions: 5
import type { Question } from "@/lib/questions/types";

export const FE_QUESTIONS_2024_CBT_KAMOKU_B: Question[] = [
  {
    "id": "fe-2024cbt-kamoku-b-q1",
    "exam": "fe",
    "session": "kamoku-b",
    "year": 2024,
    "season": "cbt",
    "qNumber": 1,
    "type": "multiple-choice",
    "category": "アルゴリズムとプログラミング",
    "topicTags": [],
    "difficulty": 3,
    "question": "次のプログラム中の に入れる正しい答えを,解答群の中から選べ。\n関数 maximum は,異なる三つの整数を引数で受け取り,そのうちの最大値を返す。\n〔プログラム〕\n○整数型:maximum(整数型:x,整数型:y,整数型:z)\nif ( )\nreturn x\nelseif (y > z)\nreturn y\nelse\nreturn z\nendif",
    "choices": {
      "ア": "x > y",
      "イ": "x > y and x > z",
      "ウ": "x > y and y > z",
      "エ": "x > z",
      "オ": "x > z and z > y",
      "カ": "z > y"
    },
    "answer": "イ",
    "explanation": "正解はイです。AIコパイロットで詳しい解説を確認してください。",
    "hasImage": false,
    "sourcePdfUrl": "https://www.jitec.ipa.go.jp/1_04hanni_sukiru/mondai_kaitou_2024h06_1/2024h06h_fe_kamoku-b_qs.pdf",
    "license": "IPA-public"
  },
  {
    "id": "fe-2024cbt-kamoku-b-q2",
    "exam": "fe",
    "session": "kamoku-b",
    "year": 2024,
    "season": "cbt",
    "qNumber": 2,
    "type": "multiple-choice",
    "category": "アルゴリズムとプログラミング",
    "topicTags": [],
    "difficulty": 3,
    "question": "次のプログラム中の に入れる正しい答えを,解答群の中から選べ。\n関数 convDecimal は,引数として与えられた,“0”と“1”だけから成る,1 文字以上の文字列を,符号なしの2進数と解釈したときの整数値を返す。例えば,引数として“10010”を与えると 18 が返る。\n関数 convDecimal が利用する関数 int は,引数で与えられた文字が“0”なら整数値0を返し、“1”なら整数値1を返す。\n[プログラム]\n○整数型:convDecimal(文字列型:binary)\n整数型:i, length, result ← 0\nlength ← binaryの文字数\nfor(iを1から length まで 1 ずつ増やす)\nresult ← \nendfor\nreturn result",
    "choices": {
      "ア": "result + int(binary の(length - i + 1)文字目の文字)",
      "イ": "result + int(binary の i文字目の文字)",
      "ウ": "result × 2 + int(binary の(length - i + 1)文字目の文字)",
      "エ": "result × 2 + int(binary の i文字目の文字)"
    },
    "answer": "エ",
    "explanation": "正解はエです。AIコパイロットで詳しい解説を確認してください。",
    "hasImage": false,
    "sourcePdfUrl": "https://www.jitec.ipa.go.jp/1_04hanni_sukiru/mondai_kaitou_2024h06_1/2024h06h_fe_kamoku-b_qs.pdf",
    "license": "IPA-public"
  },
  {
    "id": "fe-2024cbt-kamoku-b-q3",
    "exam": "fe",
    "session": "kamoku-b",
    "year": 2024,
    "season": "cbt",
    "qNumber": 3,
    "type": "multiple-choice",
    "category": "アルゴリズムとプログラミング",
    "topicTags": [],
    "difficulty": 3,
    "question": "次のプログラム中の に入れる正しい答えを,解答群の中から選べ。ここで,配列の要素番号は1から始まる。\n図1に示すグラフの頂点には,1から順に整数で番号が付けられている。グラフは無向グラフであり,各頂点間には高々ーつの辺がある。一つの辺は両端の頂点の番号を要素にもつ要素数2の整数型の配列で表現できる。例えば,{1,3}は頂点 1 と頂点3を端点とする辺を表す。グラフ全体は,グラフに含まれる辺を表す要素数2の配列を全て格納した配列(以下,辺の配列という)で表現できる。辺の配列の要素数はグラフの辺の個数と等しい。図1のグラフは整数型配列の配列{{1,3}, {1,4}, {3,4}, {2, 4}, {4,5}}と表現できる。\n関数 edgesToMatrix は,引数 edgeList で辺の配列を,引数 nodeNum でグラフの頂点の個数をそれぞれ受け取り、隣接行列を表す整数型の二次元配列を返す。\n[プログラム]\n○整数型の二次元配列: edgesToMatrix(整数型配列の配列: edgeList,\n整数型: nodeNum)\n整数型の二次元配列: adjMatrix ← {nodeNum行nodeNum列の 0}\n整数型:i, u, v\nfor(iを1から edgeListの要素数 まで 1 ずつ増やす)\nu← edgeList[i][1]\nv← edgeList[i][2]\n \nendfor\nreturn adjMatrix",
    "choices": {
      "ア": "adjMatrix[u, u] ← 1",
      "イ": "adjMatrix[u, u] ← 1\nadjMatrix[v, v] ← 1",
      "ウ": "adjMatrix[u, v] ← 1",
      "エ": "adjMatrix[u, v] ← 1\nadjMatrix[v, u] ← 1",
      "オ": "adjMatrix[v, u] ← 1",
      "カ": "adjMatrix[v, v] ← 1"
    },
    "answer": "エ",
    "explanation": "正解はエです。（出典: IPA 基本情報技術者試験 令和6年度CBT 科目B 問3）",
    "hasImage": true,
    "sourcePdfUrl": "https://www.jitec.ipa.go.jp/1_04hanni_sukiru/mondai_kaitou_2024h06_1/2024h06h_fe_kamoku-b_qs.pdf",
    "license": "IPA-public"
  },
  {
    "id": "fe-2024cbt-kamoku-b-q4",
    "exam": "fe",
    "session": "kamoku-b",
    "year": 2024,
    "season": "cbt",
    "qNumber": 4,
    "type": "multiple-choice",
    "category": "アルゴリズムとプログラミング",
    "topicTags": [],
    "difficulty": 3,
    "question": "次の記述中の に入れる正しい答えを,解答群の中から選べ。ここで,配列の要素番号は1から始まる。\n関数 merge は,昇順に整列された整数型の配列 data1 及び data2 を受け取り,これらを併合してできる昇順に整列された整数型の配列を返す。\n関数 merge を merge({2, 3},{1,4})として呼び出すと, /*** α ***/ の行は 。\n[プログラム]\n○整数型の配列: merge(整数型の配列:data1, 整数型の配列:data2)\n整数型:n1 ← data1の要素数\n整数型:n2 ← data2の要素数\n整数型の配列: work ← {(n1 + n2)個の 未定義の値}\n整数型:i←1\n整数型:j←1\n整数型:k←1\nwhile((i ≤ n1) and (j ≤ n2))\nif (data1[i] ≤ data2[j])\nwork[k] ← data1[i]\ni←i+1\nelse\nwork[k] ← data2[j]\nj←j+1\nendif\nk←k+1\nendwhile\nwhile (i ≤ n1)\nwork[k] ← data1[i]\ni←i+1\nk←k+1\nendwhile\nwhile (j ≤ n2)\nwork[k] ← data2[j] /*** α ***/\nj←j+1\nk←k+1\nendwhile\nreturn work",
    "choices": {
      "ア": "実行されない",
      "イ": "1回実行される",
      "ウ": "2回実行される",
      "エ": "3回実行される"
    },
    "answer": "イ",
    "explanation": "正解はイです。AIコパイロットで詳しい解説を確認してください。",
    "hasImage": false,
    "sourcePdfUrl": "https://www.jitec.ipa.go.jp/1_04hanni_sukiru/mondai_kaitou_2024h06_1/2024h06h_fe_kamoku-b_qs.pdf",
    "license": "IPA-public"
  },
  {
    "id": "fe-2024cbt-kamoku-b-q6",
    "exam": "fe",
    "session": "kamoku-b",
    "year": 2024,
    "season": "cbt",
    "qNumber": 6,
    "type": "multiple-choice",
    "category": "アルゴリズムとプログラミング",
    "topicTags": [],
    "difficulty": 3,
    "question": "A社は従業員 450 名の商社であり,昨年から働き方改革の一環として,在宅でのテレワークを推進している。A社のシステム環境を図1に示す。\n・従業員には,一人に1台デスクトップPC(以下,社内PCという)を貸与している。\n・従業員が利用するシステムには、自社で開発し A 社に設置している業務システムのほかに,次の二つの SaaS(以下,二つの SaaS を A 社利用クラウドサービスという)がある。\n1. メール機能,チャット機能及びクラウドストレージ機能をもつグループウェア\n(以下,A社利用グループウェアという)\n2. オンライン会議サービス\n・テレワークでは,従業員の個人所有 PC(以下,私有 PC という)の業務利用(BYOD)を許可している。\n・テレワークでは、社内 PC 及び私有 PC のそれぞれに専用のアプリケーションソフトウェア(以下,専用アプリという)を導入し、社内 PC のデスクトップから私有 PC に画面転送を行うリモートデスクトップ方式を採用している。\n・専用アプリには,リモートデスクトップから PC へのファイルのダウンロード及びファイル,文字列,画像などのコピー&ペーストを禁止する機能(以下,保存禁止機能という)があり、A社では私有 PC に対して当該機能を有効にしている。\n・業務システムには、社内 PC のデスクトップから利用者 ID 及びパスワードを入力してログインしている。\n・A 社利用クラウドサービスへのログインは,A 社利用クラウドサービス側の設定によって A 社の社内ネットワークからだけ可能になるように制限している。ログインには利用者 ID及びパスワードを用いている。\n図1 A社のシステム環境(抜粋)\nテレワークの定着が進むにつれて,社内 PC からインターネットへの接続が極端に遅くなり、業務に支障をきたしているので改善できないかと、従業員から問合せがあった。A社の社内ネットワークとインターネットとの間の通信量を調査したところ,テレワーク導入前に比べ,業務時間帯で顕著に増加したことが判明した。そのため、情報システム部では,テレワークでA社利用クラウドサービスに接続する場合には,A 社の社内ネットワークも社内 PC も介さずに直接接続することを可能にするネットワークの設定変更を実施することにした。設定変更に当たり、情報セキュリティ上の問題がないかをA社の情報セキュリティリーダーであるBさんが検討したところ,幾つか問題があることが分かった。その一つは,A 社利用クラウドサービスへの不正アクセスのリスクが増加することである。そこでBさんは,リスクを低減するために,情報システム部に対策を依頼することにした。\n設問次の対策のうち、情報システム部に依頼することにしたものはどれか。解答群のうち、最も適切なものを選べ。",
    "choices": {
      "ア": "A社の社内ネットワークからA社利用クラウドサービスへの通信を監視する。",
      "イ": "A社の社内ネットワークと A 社利用クラウドサービスとの間の通信速度を制限する。",
      "ウ": "A社利用クラウドサービスにA社外から接続する際の認証に2要素認証を導入する。",
      "エ": "A社利用クラウドサービスのうち,A 社利用グループウェアだけを直接接続の対象とする。",
      "オ": "専用アプリの保存禁止機能を無効にする。"
    },
    "answer": "ウ",
    "explanation": "正解はウです。（出典: IPA 基本情報技術者試験 令和6年度CBT 科目B 問6）",
    "hasImage": true,
    "sourcePdfUrl": "https://www.jitec.ipa.go.jp/1_04hanni_sukiru/mondai_kaitou_2024h06_1/2024h06h_fe_kamoku-b_qs.pdf",
    "license": "IPA-public"
  }
];
