// Auto-generated by scripts/parse-all.ts — do not edit manually.
// Source: IPA 基本情報技術者試験 2025年度秋期 科目B
// Questions: 2
import type { Question } from "@/lib/questions/types";

export const FE_QUESTIONS_2025_CBT_KAMOKU_B: Question[] = [
  {
    "id": "fe-2025cbt-kamoku-b-q2",
    "exam": "fe",
    "session": "kamoku-b",
    "year": 2025,
    "season": "cbt",
    "qNumber": 2,
    "type": "multiple-choice",
    "category": "アルゴリズムとプログラミング",
    "topicTags": [],
    "difficulty": 3,
    "question": "問2 次のプログラム中の に入れる正しい答えを,解答群の中から選べ。\n関数 change は,10より大きい整数を引数 n で受け取り,1円玉,5円玉,10 円玉を使ってちょうどn円にする組合せの総数を返す。\n例えば,12 円にする組合せは,次のように数えられる。10 円玉を使わない場合には、1円玉と5円玉だけでちょうど12円にすることになる。その組合せは,使える5円玉の枚数が0以上(12 ÷ 5 の商)以下なので,(12 ÷ 5 の商)+ 1 = 3通りある。同様に、10円玉を1枚使う場合には,1円玉と5円玉だけでちょうど2円にする ことになり,その組合せは(2 ÷ 5 の商)+ 1 = 1 通りある。10 円玉を 2枚以上使う組合せはない。よって,1円玉,5 円玉,10 円玉を使ってちょうど 12 円にする組合せは,3 + 1 = 4通りである。\n[プログラム]\n○整数型:change(整数型:n)\n整数型:count ← 0\n整数型: rest ← n\nwhile (\n)\n count ← count + (rest ÷ 5 の商) + 1\n rest ← rest - 10\nendwhile\nreturn count",
    "choices": {
      "ア": "rest ≥ 0",
      "イ": "rest ≥ 5",
      "ウ": "rest ≥ 10",
      "エ": "rest > 0",
      "オ": "rest > 5",
      "カ": "rest > 10"
    },
    "answer": "ア",
    "explanation": "正解はアです。AIコパイロットで詳しい解説を確認してください。",
    "hasImage": false,
    "sourcePdfUrl": "https://www.jitec.ipa.go.jp/1_04hanni_sukiru/mondai_kaitou_2025h07_1/2025h07h_fe_kamoku-b_qs.pdf",
    "license": "IPA-public"
  },
  {
    "id": "fe-2025cbt-kamoku-b-q3",
    "exam": "fe",
    "session": "kamoku-b",
    "year": 2025,
    "season": "cbt",
    "qNumber": 3,
    "type": "multiple-choice",
    "category": "アルゴリズムとプログラミング",
    "topicTags": [],
    "difficulty": 3,
    "question": "問3 次のプログラム中の a と b に入れる正しい答えの組合せを,解答群の中から選べ。ここで,配列の要素番号は1から始まる。\n関数 push は、引数で与えられた整数をスタックに格納する。格納できた場合は true を返し、格納できなかった場合は false を返す。\n関数 pop は,スタックから値を取り出して返す。スタックが空のときは未定義の値を返す。\nスタックを,要素数が4である大域の整数型の配列 stack, 及び次に値を格納する位置を示す大域の変数 stackPos で表現する。スタックの初期状態を図に示す。\nプログラムでは,配列の領域外を参照してはならないものとする。\n[プログラム]\n大域:整数型: stackPos ← 3\n大域:整数型の配列: stack ← {4,3,未定義の値,未定義の値}\n○論理型:push(整数型: inputData)\nif (stackPos ≦ stackの要素数)\n stack[ a ] ← inputData\n stackPos ← stackPos + 1\n return true\nelse\n return false\nendif\n\n○整数型:pop()\n整数型:popData ← 未定義の値\nif (stackPos > 1)\n stackPos ← b\n popData ← stack[stackPos]\n stack[stackPos] ← 未定義の値\nendif\nreturn popData",
    "choices": {
      "ア": "a: stackPos, b: stackPos + 1",
      "イ": "a: stackPos, b: stackPos - 1",
      "ウ": "a: stackPos - 1, b: stackPos + 1",
      "エ": "a: stackPos - 1, b: stackPos - 1"
    },
    "answer": "イ",
    "explanation": "正解はイです。（出典: IPA 基本情報技術者試験 令和7年度CBT 科目B 問3）",
    "hasImage": true,
    "sourcePdfUrl": "https://www.jitec.ipa.go.jp/1_04hanni_sukiru/mondai_kaitou_2025h07_1/2025h07h_fe_kamoku-b_qs.pdf",
    "license": "IPA-public"
  }
];
